### PR TITLE
refactor(analysis endpoint session handling)

### PR DESCRIPTION
**Pull request by ChrOertlin**
### Added

Move database statements out of analysis api

### Fixed

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by seallard — APPROVED** [review]
Nice! Next step could be to add a service layer to further decouple the database layer from the api layer.

api layer -> service layer -> database layer (database records) -> service layer (convert database records to dto) -> api layer (serialize dto to json).

Could make it simpler to decouple the dtos and database models.

**Comment by ChrOertlin** [comment]
> Nice! Next step could be to add a service layer to further decouple the database layer from the api layer.
> 
> api layer (parse json to dto) -> service layer -> database layer (database records) -> service layer (convert database records to dto) -> api layer (serialize dto to json).
> 
> Could make it simpler to decouple the dtos and database models. This is FastAPI though, seems like some of it is built in already

Yes, SQLModel is made to directly translate database models to DTOs for FastAPI. But we would like to detangle the CRUD and the API and remove SQLmodel. So we will implement the structure you outlined here for genotype as well! That way it is the same as in our other repos, and to me much clearer to work with.

**Comment by ChrOertlin** [comment]
## Application loads
image

**Comment by ChrOertlin** [comment]
image

**Comment by ChrOertlin** [comment]
#88

**Pull request merged**
