### PR TITLE
fix(pydantic)

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Fixed

- Missing imports

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### API 👍 
Screenshot 2024-03-05 at 16 05 55

**Review by ChrOertlin — APPROVED** [review]
Looks good

**Review by islean — APPROVED** [review]
Nice! So new ones are email-validator and python-multipart and requests?

**Comment by henrikstranneheim** [comment]
and pydantic

**Comment by henrikstranneheim** [comment]
Deployed in prod

**Pull request merged**
